### PR TITLE
Fixes #182 Allow overriding appspec path + fallback to appspec.yml and appspec.yaml

### LINKED ISSUE #182: Allow for .yaml extension of appspec
According to this one:

https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml/21059164

**.yaml is the preferred extension to .yml**

I think it does make sense that appspec could be appspec.yml AND appspec.yaml. A current codeDeploy task with appspec.yaml instead of appspec.yml fails with:

`The CodeDeploy agent did not find an AppSpec file within the unpacked revision directory at revision-relative path "appspec.yml". The revision was unpacked to directory .... ... ...`

The proper approach should be to allow for the deprecated .yml format but also to allow for .yaml file as that's the recommended extension.

### PR DESCRIPTION
**Pull request by lc-nyovchev**
### What
Fixes [#182](https://github.com/aws/aws-codedeploy-agent/issues/182): Allow for .yaml extension for appspec.

### What is actually happening under the hood

Now we allow for a **new parameter:**

`--appspec-filename`

Which allows us to specify (and thus override) an alternative name to the **previously hardcoded** `appspec.yml` file. 
If the `--appspec-filename` variable is **not set**, then it **defaults** to: `appspec.yml` _(which is the old value)_

Additionally, if this parameter is set but we **fail to find the file it points to in the root dir**, we fallback to (in that order):

- `appspec.yaml`
- `appspec.yml`
 

### Acknowledgement of License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### Additional notes:
@yubangxi if we are merging this, it'd be a good idea to also update the info in the [doc](https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html#appspec-reference-server) to reflect that.

### CODE REVIEW

File: lib/instance_agent/plugins/codedeploy/command_executor.rb [hunk 1]
```diff
@@ -473,6 +473,24 @@ def app_spec_path
...
         end
 
+        # Checks for existence the possible extensions of the app_spec_path (.yml and .yaml)
+        private
+        def app_spec_real_path(deployment_spec)
+          app_spec_yaml_location = File.join(archive_root_dir(deployment_spec), "appspec.yaml")
+          app_spec_yml_location = File.join(archive_root_dir(deployment_spec), "appspec.yml")
+          app_spec_default_location = File.join(archive_root_dir(deployment_spec), deployment_spec.app_spec_path)
+          if File.exist? app_spec_default_location
+            log(:debug, "BBBBB Using appspec file #{app_spec_default_location}")
```
Comment (nokite) [inline lib/instance_agent/plugins/codedeploy/command_executor.rb:483]: No clue what "BBBBB" is

File: lib/instance_agent/plugins/codedeploy/command_executor.rb [hunk 2]
```diff
@@ -473,6 +473,24 @@ def app_spec_path
...
+            app_spec_default_location
+          elsif File.exist? app_spec_yaml_location
+            log(:debug, "Using appspec file ${app_spec_yaml_location}")
+            app_spec_yaml_location
+          else
```
Comment (nokite) [inline lib/instance_agent/plugins/codedeploy/command_executor.rb:488]: would it be smart to also check whether yml exists? Then you could throw a descriptive error.

if yes, then:
(minor) About order - is the yaml or the yml location more likely?

File: lib/instance_agent/plugins/codedeploy/command_executor.rb [hunk 3]
```diff
@@ -473,6 +473,24 @@ def app_spec_path
           'appspec.yml'
         end
 
+        # Checks for existence the possible extensions of the app_spec_path (.yml and .yaml)
+        private
+        def app_spec_real_path(deployment_spec)
+          app_spec_yaml_location = File.join(archive_root_dir(deployment_spec), "appspec.yaml")
+          app_spec_yml_location = File.join(archive_root_dir(deployment_spec), "appspec.yml")
+          app_spec_default_location = File.join(archive_root_dir(deployment_spec), deployment_spec.app_spec_path)
```
Comment (nokite) [inline lib/instance_agent/plugins/codedeploy/command_executor.rb:481]: I wouldn't call app_spec_default_location "default", it's more of an override, right?
The other two could include "default" in their names.

File: lib/instance_agent/plugins/codedeploy/command_executor.rb [hunk 4]
```diff
@@ -192,18 +192,18 @@ def most_recent_deployment_dir(deployment_group)
...
-          end 
+          end
         end
 
         private
         def default_app_spec(deployment_spec)
-          default_app_spec_location = File.join(archive_root_dir(deployment_spec), app_spec_path)
-          log(:debug, "Checking for app spec in #{default_app_spec_location}")
-          validate_app_spec_hooks(ApplicationSpecification::ApplicationSpecification.parse(File.read(default_app_spec_location)), deployment_spec.all_possible_lifecycle_events)
+          app_spec_location = app_spec_real_path(deployment_spec)
```
Comment (nokite) [inline lib/instance_agent/plugins/codedeploy/command_executor.rb:200]: I haven't checked the calling code, but make sure the name default_app_spec still makes sense (its variable now).

**Review by nokite — COMMENTED** [review]
Nice change and good job with the tests

File: lib/instance_agent/plugins/codedeploy/command_executor.rb (hunk 4 above)
Comment (lc-nyovchev) [reply lib/instance_agent/plugins/codedeploy/command_executor.rb:200]: I believe having it as `default_app_spec` doesn't make sense, since we are determining. I renamed it to: `app_spec_location` to signify that.

File: lib/instance_agent/plugins/codedeploy/command_executor.rb (hunk 1 above)
Comment (lc-nyovchev) [reply lib/instance_agent/plugins/codedeploy/command_executor.rb:483]: Good catch! I think my keyboard was stuck or something. Will remove it.

File: lib/instance_agent/plugins/codedeploy/command_executor.rb (hunk 2 above)
Comment (lc-nyovchev) [reply lib/instance_agent/plugins/codedeploy/command_executor.rb:488]: On the (minor) question you have:
- `yml` is the previously **hardcoded** location. 
- `yaml` is the last alternative

### Before 
Before this PR, we were just going for: `appspec.yml`, which is hardcoded.

### With this PR
we use, in the following order:
- `AppSpecPath` (a new variable you can specify via commandline). This will be the preferred location. If this param is not specified, it defaults to `appspec.yml` 
- if the file under `AppSpecPath` doesn't exist, the argument is not specified, we try with `appspec.yaml`
- if even the `appspec.yaml` doesn't exist, we try as last resort the `appspec.yml`

File: lib/instance_agent/plugins/codedeploy/command_executor.rb (hunk 3 above)
Comment (lc-nyovchev) [reply lib/instance_agent/plugins/codedeploy/command_executor.rb]: Makes sense, indeed this is the only one! I changed it to reflect what you proposed.

File: lib/instance_agent/plugins/codedeploy/command_executor.rb (hunk 2 above)
Comment (nokite) [reply lib/instance_agent/plugins/codedeploy/command_executor.rb:488]: I don't have a hard opinion, just pointing out that the behavior would now be changed for people who have both appspec.yml and appspec.yaml. That's why I though that the previous hardcoded value should come first (well, after the override, of course). Up to you.

**Review by nokite — APPROVED** [review]
🎸 🤘

**Comment by lc-nyovchev** [comment]
Closed/reopened in order to trigger travis rebuild

**Comment by lc-nyovchev** [comment]
@yubangxi or @rohkat-aws do you guys mind re-running the travis build on the PR as I added new tests? Seems reopening/closing or new commits don't help.

**Comment by lc-nyovchev** [comment]
@vrr-21 I was wondering if you'd be able to review this one? I merged upstream changes from master so the conflicts are now resolved.

**Comment by philstrong** [comment]
This is a great change, testing on our end then we'll get this merged in.
