### PR TITLE
Make restart actually work

### LINKED ISSUE #24: Restart does not work
Really??

screen shot 2015-08-28 at 10 53 59 am

### PR DESCRIPTION
**Pull request by jdrago999**
fixes #24

### CODE REVIEW

File: init.d/codedeploy-agent [hunk 1]
```diff
@@ -40,6 +40,13 @@ stop() {
         exit $?
 }
 
+restart() {
+        echo -n $"Stopping $prog:"
```
Comment (suryanarayanan) [inline init.d/codedeploy-agent]: Can you change the text 'Stopping' to 'Restarting' ?
